### ISSUE TITLE
Fix mail config problem

### ISSUE THREAD

**Issue by hallvors** [mozilla/compatipede#47]
Log says:

```
2016-02-26T01:42:14.036Z - ESC[31merrorESC[39m: [Email] Failed to send email Error: Failed to send email. cause: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it
    at Nodemailer.sendMail (/opt/compatipede/node_modules/nodemailer/lib/nodemailer.js:173:25)
    at /opt/compatipede/lib/email.js:70:23
    at /opt/compatipede/lib/models/email.js:28:7
```

I suppose we can just order a lower version of nodemailer in package.json?

**Comment by hallvors** [comment]
(Note to self: this is a bit too specific about the Moz infrastructure, should perhaps have reported it in Bugzilla instead of here)

**Comment by hallvors** [comment]
Was as simple as adding smtp:// on the command line :)
